- type: startingGear
  id: CBURNFlamerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackFlameTank
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitCBURN
    shoes: ClothingShoesBootsCombatFilled
    id: CBURNPDA
    pocket1: RadioHandheld
    pocket2: WeaponLaserGun
    suitstorage: OxygenTankFilled
    belt: ClothingBeltBandolier
  inhand:
    - WeaponSprayNozzle
  innerClothingSkirt: ClothingUniformJumpsuitColorBrown
  # satchel: ClothingBackpackDuffelCBURNFilled
  # duffelbag: ClothingBackpackDuffelCBURNFilled
